# indexing

In [9]:
import numpy as np
a=[]
size=int(input("enter size: "))
for i in range(size):
    val=int(input(" ehter number : "))
    a.append(val)
arr1=np.array(a)
for i in range(arr1.size):
    print(arr1[i])
sum=0
for i in range(arr1.size):
    sum+=arr1[i]
print(sum)

enter size: 5
 ehter number : 1
 ehter number : 2
 ehter number : 3
 ehter number : 4
 ehter number : 5
1
2
3
4
5
15


# Slicing

In [10]:
arr2=arr1[2:4]
print(arr2)

[3 4]


In [12]:
v=arr1[1:]

In [13]:
v

array([2, 3, 4, 5])

# Reshaping

In [14]:
import numpy as np

In [15]:
arr=np.random.randint(1,50,12)
arr

array([17, 12,  1, 26, 39, 10, 47, 32, 11, 49, 48,  3])

In [16]:
arr.shape

(12,)

In [17]:
type(arr)

numpy.ndarray

1D to 2D

In [18]:
arr1=arr.reshape(2,6)

In [19]:
arr1

array([[17, 12,  1, 26, 39, 10],
       [47, 32, 11, 49, 48,  3]])

In [20]:
arr2=arr.reshape(3,4)

In [21]:
arr2

array([[17, 12,  1, 26],
       [39, 10, 47, 32],
       [11, 49, 48,  3]])

2D to 1D

In [27]:
arr2=arr2.reshape(12)

In [28]:
arr2

array([17, 12,  1, 26, 39, 10, 47, 32, 11, 49, 48,  3])

1D to 3D

In [30]:
arr2=arr2.reshape(2,2,3)

In [31]:
arr2

array([[[17, 12,  1],
        [26, 39, 10]],

       [[47, 32, 11],
        [49, 48,  3]]])

# Seed function

In [32]:
import numpy as np

In [33]:
np.random.seed(12)
arr=np.random.randint(1,100,10)
arr

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50])

In [34]:
np.random.seed(2)
arr=np.random.randint(1,100,10)
arr

array([41, 16, 73, 23, 44, 83, 76,  8, 35, 50])

In [36]:

arr=np.random.randint(1,100,10)
arr

array([68,  5, 43, 52, 39, 34, 59, 68, 70, 89])

# creating 2d array of user defined

In [44]:
import numpy as np
matrix=[]
row=int(input("enter number of rows: "))
col=int(input("enter number of columns: "))
for i in range(row):
    a=[]
    for j in range(col):
        val=int(input("enter number :"))
        a.append(val)
    matrix.append(a)
arr=np.array(matrix)
for i in range(row):
    for j in range(col):
        print(arr[i][j],end=' ')
    print()
        

enter number of rows: 3
enter number of columns: 3
enter number :1
enter number :2
enter number :3
enter number :4
enter number :5
enter number :6
enter number :7
enter number :8
enter number :9
1 2 3 
4 5 6 
7 8 9 


In [45]:
type(arr)


numpy.ndarray

# slicing 2D Array

In [46]:
import numpy as np
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [47]:
#a[row:column]
a[:1]

array([[10, 20, 30]])