# sclicing

In [6]:
import numpy as np
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
a

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [7]:
a[:2,1:3]

array([[20, 30],
       [50, 60]])

In [8]:
import numpy as np
np.random.seed(111)
a=np.random.randint(1,500,30).reshape(6,5)
a

array([[341, 365, 469, 213,  87],
       [276, 170, 323, 119, 467],
       [297, 456, 442,   8, 269],
       [267, 450, 369, 217, 285],
       [271, 419,  22,  55, 201],
       [ 38, 461, 231, 187, 269]])

In [10]:
a[2:,2:]

array([[442,   8, 269],
       [369, 217, 285],
       [ 22,  55, 201],
       [231, 187, 269]])

In [13]:
a[3:5,2:]

array([[369, 217, 285],
       [ 22,  55, 201]])

# View vs copy

In [15]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80])
slicing=a[3:6]
slicing[:]=0
a

array([10, 20, 30,  0,  0,  0, 70, 80])

In [16]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80])
slicing=a[3:6].copy()
slicing[:]=0
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [17]:
slicing

array([0, 0, 0])

# conditional selectional

In [22]:
import numpy as np
arr=np.arange(1,16)
b=arr>10
arr[b]

array([11, 12, 13, 14, 15])

In [23]:
arr[arr<5]

array([1, 2, 3, 4])

In [24]:
arr[arr%2==0]=0

In [25]:
arr

array([ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15])

In [26]:
arr[arr%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

# various operations on numpy array

In [45]:
import numpy as np
a=np.arange(1,6)
b=np.arange(6,11)
print(a)
print(b)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [46]:
a*2

array([ 2,  4,  6,  8, 10])

In [47]:
a+2

array([3, 4, 5, 6, 7])

In [48]:
a**a

array([   1,    4,   27,  256, 3125], dtype=int32)

In [49]:
a+b

array([ 7,  9, 11, 13, 15])

In [50]:
a-b

array([-5, -5, -5, -5, -5])

In [51]:
b-a

array([5, 5, 5, 5, 5])

# for 2D

In [53]:
c=np.array([1,2,3,4]).reshape(2,2)
d=np.array([5,6,7,8]).reshape(2,2)

In [54]:
c

array([[1, 2],
       [3, 4]])

In [55]:
d

array([[5, 6],
       [7, 8]])

In [56]:
c.dot(d)

array([[19, 22],
       [43, 50]])

In [57]:
c+d

array([[ 6,  8],
       [10, 12]])

In [58]:
c**d

array([[    1,    64],
       [ 2187, 65536]], dtype=int32)

In [59]:
d-c

array([[4, 4],
       [4, 4]])