In [9]:
#import numpy
import numpy as np
a=[1,2,3]
a

[1, 2, 3]

# 1 Dimensional Array

In [10]:
#import numpy & creating array
import numpy as np
a=[1,2,3]
myarr=np.array(a)
myarr

array([1, 2, 3])

In [12]:
myarr1=np.array([1,2,3,4,5])
myarr1

array([1, 2, 3, 4, 5])

In [24]:
a=[]
n=int(input("enter size of array :"))
for i in range(n):
    val=int(input("enter number :"))
    a.append(val)
myarray=np.array(a)
myarray

enter size of array :5
enter number :1
enter number :3
enter number :2
enter number :55
enter number :4


array([ 1,  3,  2, 55,  4])

In [27]:
myarray.sort()

In [28]:
myarray

array([ 1,  2,  3,  4, 55])

# 2 Dimensional Array

In [29]:
import numpy as np
a=[[1,2,3],[4,5,6],[7,8,9]]
myarray=np.array(a)
myarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
myarray.ndim

2

In [31]:
myarray.shape

(3, 3)

In [32]:
type(myarray)

numpy.ndarray

# function zero

In [34]:
a=np.zeros(4)
a

array([0., 0., 0., 0.])

# ones

In [35]:
a=np.ones(4)
a

array([1., 1., 1., 1.])

In [36]:
a=np.ones([2,3])
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [39]:
a=np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

# eye

In [41]:
a=np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# diag

In [42]:
arr=np.diag([1,2,3])
arr

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [43]:
np.diag(arr)

array([1, 2, 3])

# randint

In [45]:
arr1=np.random.randint(1,10,3)
arr1

array([4, 5, 6])

# Rand

In [46]:
arr1=np.random.rand(5)
arr1

array([0.29548615, 0.97959285, 0.81096136, 0.04919044, 0.82568819])

In [47]:
arr1=np.random.rand(2,3)
arr1

array([[0.933644  , 0.0777765 , 0.87990858],
       [0.52691914, 0.59219475, 0.6702828 ]])

In [48]:
arr1=np.random.randn(5)
arr1

array([-0.24877155, -0.3148437 , -0.6488811 ,  0.89412729, -0.32418528])

# Indexing & slicing