In [1]:
import numpy as np
np.random.seed(122)
arr=np.random.randint(1,21,10)
arr

array([16, 11, 13, 17, 13, 16,  3, 16, 11, 10])

In [2]:
np.random.shuffle(arr)

In [4]:
arr

array([13, 16, 16, 11, 16, 10, 11, 13, 17,  3])

In [6]:
import numpy as np
arr=np.array([10,20,30,40,50])
np.unique(arr).size

5

In [8]:
arr=np.array([10,20,30,40,10,20,50])
np.unique(arr,return_index=True,return_counts=True)

(array([10, 20, 30, 40, 50]),
 array([0, 1, 2, 3, 6], dtype=int64),
 array([2, 2, 1, 1, 1], dtype=int64))

# numpy stacking

there are two types -1 vertical and 2 horizontal

In [9]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
import numpy as np
np.random.seed(122)
arr1=np.random.randint(1,21,9).reshape(3,3)
arr2=np.random.randint(50,71,9).reshape(3,3)
np.hstack((arr1,arr2))

array([[16, 11, 13, 59, 56, 64],
       [17, 13, 16, 53, 54, 69],
       [ 3, 16, 11, 69, 63, 50]])

In [14]:
arr1

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [15]:
arr2

array([[59, 56, 64],
       [53, 54, 69],
       [69, 63, 50]])

In [16]:
np.vstack((arr1,arr2))

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11],
       [59, 56, 64],
       [53, 54, 69],
       [69, 63, 50]])

write statement to import numpy? 

In [22]:
import numpy as np

create array using numpy

In [18]:
arr=np.array([10,20,30])

In [19]:
arr

array([10, 20, 30])

In [20]:
type(arr)

numpy.ndarray

create array of 10 random integers

In [80]:
np.random.randint(1,10,10)

array([2, 8, 4, 1, 3, 2, 1, 9, 1, 7])

In [82]:
np.random.randint(10,20,10)

array([13, 14, 12, 19, 10, 15, 13, 12, 18, 15])

In [81]:
np.random.rand(10)

array([0.08796029, 0.86655401, 0.66179251, 0.63151183, 0.29124995,
       0.96040431, 0.85445975, 0.09333718, 0.32707117, 0.20358237])

create array which contain value 5 (10 times)

In [55]:
a=np.array([5]*10)
a    
   
   

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [57]:
import numpy as np

output = np.ones(10, dtype=int) * 5
print(output)


[5 5 5 5 5 5 5 5 5 5]


In [89]:
%%timeit
a=np.array([])
for i in range(11):
    a=np.append(a,5 )

a


74.5 µs ± 12 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


create 1D array and convert into 3*3 matrix

In [75]:
b=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)

In [76]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
type(b)

numpy.ndarray

create array and then convert all even number with zero

In [88]:
arr=np.array([1,2,3,4,5,6])
for i in range (len(arr)):
    if arr[i]%2==0:
        arr[i]=0
print(arr)
        

[1 0 3 0 5 0]


In [90]:
%timeit [i**2 for i in range(1,11)]

4.35 µs ± 63.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [91]:
import numpy as np
%timeit np.arange(1,11)**2

1.95 µs ± 61.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


searching in numpy

In [111]:
arr=np.array([1,2,3,4,5])
search=int(input(" search number: "))

for i in range(len(arr)):
    if arr[i]==search:
        print('found')
        break
  
print('index number is',i)
    

 search number: 5
found
index number is 4


In [105]:
x=np.where(arr==5)
print(x)

(array([4], dtype=int64),)


In [118]:
a=np.array([1,5,8,9,12])
x=np.searchsorted(a,7)
print(x)

2


In [119]:
sorted(a)

[1, 5, 8, 9, 12]