# Numpy array function

In [1]:
import numpy as np

In [2]:
arr=np.array([10,20,30,40,50])

In [3]:
arr

array([10, 20, 30, 40, 50])

In [4]:
np.min(arr)

10

In [5]:
np.max(arr)

50

In [6]:
np.argmin(arr) # arg gives index number of given array ehich has minimum value

0

In [7]:
np.argmax(arr)

4

In [8]:
np.sqrt(arr)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [9]:
np.sin(arr)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [10]:
np.cos(arr)

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806,  0.96496603])

# linspace

In [11]:
np.linspace(1,2,5) # it gives number in between 1 to 2 which gives 5 elements and have same difference between them

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

# for 2D array

In [12]:
import numpy as np
np.random.seed(122)
matrix=np.random.randint(1,21,9).reshape(3,3)

In [13]:
matrix

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [14]:
np.sum(matrix)

116

In [15]:
matrix.sum()

116

In [16]:
np.min(matrix)

3

In [17]:
np.max(matrix)

17

In [18]:
np.min(matrix, axis=0) # axis=0 -> col wise min

array([ 3, 11, 11])

In [19]:
np.max(matrix,axis=0)

array([17, 16, 16])

In [20]:
np.min(matrix, axis=1)

array([11, 13,  3])

In [21]:
np.max(matrix,axis=1)

array([16, 17, 16])

In [ ]:
np.cumsum(ma)